apiVersion: v1
kind: Secret
metadata:
  name: database-config
type: Opaque
data:
  # Fill in your own configuration and use base64 for encoding and paste it here.
  host:
  port:
  username:
  password:
  database_name:
