name: Publish Docker Image

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
        -
          name: Checkout
          uses: actions/checkout@v2
        -
          name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: 12
        -
          name: Cache NPM dependencies
          uses: actions/cache@v2
          with:
            path: ~/.npm
            key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.OS }}-npm-cache-
        -
          name: Install dependencies
          run: npm ci
        -
          name: Build project
          run: npm run build
  publish:
    name: Publish
    runs-on: ubuntu-18.04
    needs:
      - build
    steps:
      # Generate image tag name, one is with the version number, the other is the latest version.
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/ti-sync-bot
      # The v2 version of docker/build-push-action uses Docker Buildx to build.
      -
        name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.1.1
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Image digest
        run:
          echo ${{ steps.docker_build.outputs.digest }}
